%define two character type string
char s(n);
char x(n);
%enter a word string 
s=input('Enter a word','s');
[m,n]=size(s);
for i=1:n  , s(i);
    switch s(i)
        case '¬'
            x(i)='A'
        case '«'
            x(i)='|'
        case '»'
            x(i)='b'
        case 'Å'
            x(i)='p'
        case ' '
            x(i)='t'
        case 'À'
            x(i)='V'
        case 'Ã'
            x(i)='j'
        case 'ç'
            x(i)='c'
        case 'Õ'
            x(i)='H'
        case 'Œ'
            x(i)='x'
        case 'œ'
            x(i)='d'
        case '–'
            x(i)='L'
        case '—'
            x(i)='r'
        case '“'
            x(i)='z'
        case 'é'
            x(i)='J'
        case '”'
            x(i)='s'
        case '‘'
            x(i)='C'
        case '’'
            x(i)='S'
        case '÷'
            x(i)='D'
        case 'ÿ'
            x(i)='T'
        case 'Ÿ'
            x(i)='Z'
        case '⁄'
            x(i)='E'
        case '€'
            x(i)='G'
        case '›'
            x(i)='f'
        case 'ﬁ'
            x(i)='q'
        case 'ò'
            x(i)='k'
        case 'ê'
            x(i)='g'
        case '·'
            x(i)='l'
        case '„'
            x(i)='m'
        case '‰'
            x(i)='n'
        case 'Ê'
            x(i)='u'
        case 'Â'
            x(i)='h'
        case 'Ì'
            x(i)='i'
        case 'ı'
            x(i)='o'
        case 'Û'
            x(i)='a'
        case 'ˆ'
            x(i)='e'
            
    end;
end
%see output(Pinglish Word)
z=sprintf('%s',x)